# Project information
site_name: My Super Cool Test Docs Website Project Thing
site_url: https://aeisan18.github.io/DocsWebsite
site_author: Adam Eisan

# Repository
repo_name: DocsWebsite
repo_url: https://github.com/aeisan18/DocsWebsite
edit_uri: edit/master/my-test-folder
docs_dir: my-test-folder


##########################################################################
# Navigation
##########################################################################
nav:
  - Welcome:
    - About: README.md   
    # - Stuff for Kurt: Welcome/kurt.md   
    - Stuff for Kurt: kurt.md   
  - Section2:
    - More stuff: README2.md   
  - Blog: 
    - blog/index.md
  - Tags: tags.md


## DO NOT CHANGE BELOW THIS LINE



# Copyright
# TBD



##########################################################################
# Theme
##########################################################################
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  # icon:
    # logo: material/server
  logo: assets/images/brutus-head.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: blue grey
      accent: indego

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: indego
  features:
    # - toc.integrate # moves toc from right side into left seide nav
    - toc.follow
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.expand
    - navigation.tracking
    - navigation.tabs # tabs at top
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top # back to top button
    - search.suggest
    # - search.highlight
    - search.relaated
    - search.share
    - content.code.copy
    - content.code.select




##########################################################################
# Plugins
##########################################################################
plugins:
  - search
  - tags:
      # tags_file: tags.md # line not needed anymore per documentation 
  - privacy
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


##########################################################################
# Customization
# TBD
#########################################################################


#

##########################################################################
# Extensions
##########################################################################
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde